name: publish-on-release

on:
 release:
  types: [ published ]

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
            global-json-file: global.json

      - name: publish FakeItEasy.AutoFakeIt
        id: publish_nuget_common
        uses: alirezanet/publish-nuget@v3.0.0
        with:
          PROJECT_FILE_PATH: src/FakeItEasy.AutoFakeIt/FakeItEasy.AutoFakeIt.csproj
          PACKAGE_NAME: FakeItEasy.AutoFakeIt
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          TAG_COMMIT: false
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          INCLUDE_SYMBOLS: true

